import { useEffect, useState, type ReactNode } from 'react'
import { FileText, Pencil, Save, ShieldAlert, Users, X } from 'lucide-react'
import { createGrade, listResource, type LaravelCollection, type ResourceRecord, updateGrade } from '../services/api/resourcesApi'
import { useAuth } from '../contexts/AuthContext'

const valueAt = (record: ResourceRecord, paths: string[], fallback = '-') => {
  for (const path of paths) {
    const value = path.split('.').reduce<unknown>((current, key) => current && typeof current === 'object' ? (current as Record<string, unknown>)[key] : undefined, record)
    if (value !== undefined && value !== null && value !== '') return String(value)
  }
  return fallback
}

const studentKey = (record: ResourceRecord) => valueAt(record, ['enrollment.student.student_number', 'student.student_number', 'student_number', 'enrollment.student.id', 'student.id', 'student_id'])
const studentName = (record: ResourceRecord) => valueAt(record, ['enrollment.student.name', 'enrollment.student.full_name', 'student.name', 'student.full_name'], '') || [valueAt(record, ['enrollment.student.first_name', 'student.first_name'], ''), valueAt(record, ['enrollment.student.last_name', 'student.last_name'], '')].filter(Boolean).join(' ') || 'Unknown student'
const courseName = (record: ResourceRecord) => valueAt(record, ['enrollment.course_offering.course.course_title', 'enrollment.course_offering.course.course_code', 'course_offering.course.course_title', 'course_offering.course.course_code', 'course.name', 'course.title', 'course_offering.course_code', 'course_code', 'course_name', 'course_id'])

type PageMeta = Pick<LaravelCollection<ResourceRecord>, 'current_page' | 'last_page' | 'total'>

function State({ error, empty }: { error?: string; empty?: string }) { return <div className="state">{error ? <><ShieldAlert size={28} /><p>{error}</p></> : <><FileText size={28} /><p>{empty}</p></>}</div> }
function Table({ children }: { children: ReactNode }) { return <div className="panel table-panel"><div className="table-wrap"><table>{children}</table></div></div> }
function Pagination({ meta, onPage }: { meta: PageMeta; onPage: (page: number) => void }) { return <div className="pagination"><span>{meta.total} total records</span><div><button className="secondary-button" disabled={meta.current_page <= 1} onClick={() => onPage(meta.current_page - 1)}>Previous</button><strong>{meta.current_page} / {meta.last_page}</strong><button className="secondary-button" disabled={meta.current_page >= meta.last_page} onClick={() => onPage(meta.current_page + 1)}>Next</button></div></div> }
function useRecords(endpoint: string, page: number) { const [result, setResult] = useState<LaravelCollection<ResourceRecord>>({ data: [], current_page: 1, last_page: 1, per_page: 20, total: 0 }); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); useEffect(() => { let active = true; setLoading(true); setError(''); listResource<ResourceRecord>(endpoint, { page, per_page: 20 }).then(value => { if (active) setResult(value) }).catch(requestError => { if (active) setError(requestError.response?.data?.message || `Unable to load ${endpoint.slice(1)}.`) }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [endpoint, page]); return { result, loading, error } }

function RecordsPage({ title, description, endpoint, page, setPage, children }: { title: string; description: string; endpoint: string; page: number; setPage: (page: number) => void; children: (result: LaravelCollection<ResourceRecord>) => ReactNode }) { const { result, loading, error } = useRecords(endpoint, page); return <section className="page"><div className="page-heading"><div><span className="eyebrow">Academic records</span><h2>{title}</h2><p className="muted">{description}</p></div></div>{loading ? <div className="panel state"><div className="spinner" /><p>Loading records...</p></div> : error ? <State error={error} /> : result.data.length === 0 ? <div className="panel"><State empty={`No ${title.toLowerCase()} found.`} /></div> : <>{children(result)}<Pagination meta={result} onPage={setPage} /></>}</section> }

export function EnrollmentsPage() { const [page, setPage] = useState(1); return <RecordsPage title="Enrollments" description="Students, their course offerings, and enrollment status from the API." endpoint="/enrollments" page={page} setPage={setPage}>{result => <Table><thead><tr><th>Student ID</th><th>Student name</th><th>Course</th><th>Term</th><th>Status</th></tr></thead><tbody>{result.data.map(record => <tr key={record.id}><td>{studentKey(record)}</td><td>{studentName(record)}</td><td>{courseName(record)}</td><td>{valueAt(record, ['course_offering.academic_term.academic_year', 'enrollment.course_offering.academic_term.academic_year'])}</td><td><span className={`status status-${valueAt(record, ['status'], 'unknown').toLowerCase()}`}>{valueAt(record, ['status'])}</span></td></tr>)}</tbody></Table>}</RecordsPage> }

export function SubjectsPage() { const { user } = useAuth(); return user?.role === 'STUDENT' ? <StudentSubjects /> : <SubjectRoster /> }
function StudentSubjects() { const [page, setPage] = useState(1); return <RecordsPage title="My subjects" description="Subjects and sections in which you are currently enrolled." endpoint="/enrollments" page={page} setPage={setPage}>{result => <Table><thead><tr><th>Subject</th><th>Section</th><th>Term</th><th>Schedule</th><th>Status</th></tr></thead><tbody>{result.data.map(record => <tr key={record.id}><td><strong>{valueAt(record, ['course_offering.course.course_code'])}</strong><br />{valueAt(record, ['course_offering.course.course_title'])}</td><td>{valueAt(record, ['course_offering.section'])}</td><td>{valueAt(record, ['course_offering.academic_term.academic_year'])}</td><td>{valueAt(record, ['course_offering.schedule'])}</td><td><span className={`status status-${valueAt(record, ['status'], 'unknown').toLowerCase()}`}>{valueAt(record, ['status'])}</span></td></tr>)}</tbody></Table>}</RecordsPage> }
function SubjectRoster() { const [page, setPage] = useState(1); const [selected, setSelected] = useState<ResourceRecord | null>(null); return <RecordsPage title="Subjects" description="Manage subject sections and view the students enrolled in each offering." endpoint="/course-offerings" page={page} setPage={setPage}>{result => <><Table><thead><tr><th>Subject</th><th>Section</th><th>Instructor</th><th>Term</th><th>Enrolled</th><th>Action</th></tr></thead><tbody>{result.data.map(record => <tr key={record.id}><td><strong>{valueAt(record, ['course.course_code'])}</strong><br />{valueAt(record, ['course.course_title'])}</td><td>{valueAt(record, ['section'])}</td><td>{valueAt(record, ['instructor.name', 'instructor.email'])}</td><td>{valueAt(record, ['academicTerm.academic_year', 'academic_term.academic_year'])}</td><td>{selected?.id === record.id ? 'Viewing' : 'Roster available'}</td><td><button className="text-button" onClick={() => setSelected(selected?.id === record.id ? null : record)}><Users size={14} />{selected?.id === record.id ? 'Hide students' : 'View students'}</button></td></tr>)}</tbody></Table>{selected && <OfferingRoster offering={selected} />}</>}</RecordsPage> }
function OfferingRoster({ offering }: { offering: ResourceRecord }) { const [page, setPage] = useState(1); const [reload, setReload] = useState(0); const { result, loading, error } = useRecords(`/course-offerings/${offering.id}/students?refresh=${reload}`, page); return <div className="panel"><div className="panel-heading"><div><h3>{valueAt(offering, ['course.course_code'])} enrolled students</h3><p className="muted">{valueAt(offering, ['course.course_title'])} · Section {valueAt(offering, ['section'])}</p></div></div>{loading ? <div className="state"><div className="spinner" /><p>Loading students...</p></div> : error ? <State error={error} /> : result.data.length === 0 ? <State empty="No students are enrolled in this subject." /> : <><div className="table-wrap"><table><thead><tr><th>Student number</th><th>Student name</th><th>Status</th><th>Midterm</th><th>Final</th><th>Remarks</th><th>Action</th></tr></thead><tbody>{result.data.map(record => <RosterGradeRow key={record.id} enrollment={record} onSaved={() => setReload(value => value + 1)} />)}</tbody></table></div><Pagination meta={result} onPage={setPage} /></>}</div> }
function RosterGradeRow({ enrollment, onSaved }: { enrollment: ResourceRecord; onSaved: () => void }) { const grade = enrollment.grade && typeof enrollment.grade === 'object' ? enrollment.grade as ResourceRecord : undefined; const gradeValue = (paths: string[], fallback = '') => grade ? valueAt(grade, paths, fallback) : fallback; const [editing, setEditing] = useState(!grade); const [values, setValues] = useState({ midterm_grade: gradeValue(['midterm_grade']), final_grade: gradeValue(['final_grade']), remarks: gradeValue(['remarks']) }); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); async function save() { setSaving(true); setError(''); try { if (grade) await updateGrade(grade.id, values); else await createGrade({ enrollment_id: enrollment.id, ...values }); setEditing(false); onSaved() } catch (requestError: any) { setError(requestError.response?.data?.message || 'Unable to save grade.') } finally { setSaving(false) } } const studentNumber = valueAt(enrollment, ['student.student_number']); const name = `${valueAt(enrollment, ['student.last_name'])}, ${valueAt(enrollment, ['student.first_name'])}`; if (editing) return <tr><td>{studentNumber}</td><td>{name}</td><td>{valueAt(enrollment, ['status'])}</td><td><input className="table-input" type="number" min="0" max="100" value={values.midterm_grade} onChange={event => setValues(current => ({ ...current, midterm_grade: event.target.value }))} aria-label="Midterm grade" /></td><td><input className="table-input" type="number" min="0" max="100" value={values.final_grade} onChange={event => setValues(current => ({ ...current, final_grade: event.target.value }))} aria-label="Final grade" /></td><td><input className="table-input" value={values.remarks} onChange={event => setValues(current => ({ ...current, remarks: event.target.value }))} aria-label="Grade remarks" />{error && <small className="form-error">{error}</small>}</td><td><button className="icon-button" onClick={() => void save()} disabled={saving} title="Save grade" aria-label="Save grade"><Save size={16} /></button>{grade && <button className="icon-button" onClick={() => setEditing(false)} title="Cancel" aria-label="Cancel"><X size={16} /></button>}</td></tr>; return <tr><td>{studentNumber}</td><td>{name}</td><td>{valueAt(enrollment, ['status'])}</td><td>{gradeValue(['midterm_grade'], '-')}%</td><td>{gradeValue(['final_grade'], '-')}%</td><td>{gradeValue(['remarks'], '-')}</td><td><button className="text-button" onClick={() => setEditing(true)}><Pencil size={14} />{grade ? 'Edit' : 'Assign grade'}</button></td></tr> }

export function GradesPage() { const [page, setPage] = useState(1); const [reload, setReload] = useState(0); return <GradeRecords page={page} setPage={setPage} reload={reload} onSaved={() => setReload(value => value + 1)} /> }
function GradeRecords({ page, setPage, reload, onSaved }: { page: number; setPage: (page: number) => void; reload: number; onSaved: () => void }) { const { user } = useAuth(); const { result, loading, error } = useRecords(`/grades?refresh=${reload}`, page); const canEdit = user?.role === 'ADMINISTRATOR' || user?.role === 'STAFF' || user?.role === 'INSTRUCTOR'; return <section className="page"><div className="page-heading"><div><span className="eyebrow">Academic records</span><h2>Grades</h2><p className="muted">Review every student grade and update grades for courses you are authorized to manage.</p></div></div>{loading ? <div className="panel state"><div className="spinner" /><p>Loading grades...</p></div> : error ? <State error={error} /> : result.data.length === 0 ? <div className="panel"><State empty="No grades found." /></div> : <><GradeTable records={result.data} canEdit={canEdit} onSaved={onSaved} /><Pagination meta={result} onPage={setPage} /></>}</section> }
function GradeTable({ records, canEdit, onSaved }: { records: ResourceRecord[]; canEdit: boolean; onSaved: () => void }) { return <Table><thead><tr><th>Student ID</th><th>Student name</th><th>Course</th><th>Midterm</th><th>Final</th><th>Remarks</th>{canEdit && <th>Action</th>}</tr></thead><tbody>{records.map(record => <GradeRow key={record.id} record={record} canEdit={canEdit} onSaved={onSaved} />)}</tbody></Table> }
function GradeRow({ record, canEdit, onSaved }: { record: ResourceRecord; canEdit: boolean; onSaved: () => void }) { const [editing, setEditing] = useState(false); const [values, setValues] = useState({ midterm_grade: valueAt(record, ['midterm_grade'], ''), final_grade: valueAt(record, ['final_grade'], ''), remarks: valueAt(record, ['remarks'], '') }); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); async function save() { setSaving(true); setError(''); try { await updateGrade(record.id, values); setEditing(false); onSaved() } catch (requestError: any) { setError(requestError.response?.data?.message || 'Unable to update grade.') } finally { setSaving(false) } } if (editing) return <tr><td>{studentKey(record)}</td><td>{studentName(record)}</td><td>{courseName(record)}</td><td><input className="table-input" type="number" min="0" max="100" value={values.midterm_grade} onChange={event => setValues(current => ({ ...current, midterm_grade: event.target.value }))} aria-label="Midterm grade" /></td><td><input className="table-input" type="number" min="0" max="100" value={values.final_grade} onChange={event => setValues(current => ({ ...current, final_grade: event.target.value }))} aria-label="Final grade" /></td><td><input className="table-input" value={values.remarks} onChange={event => setValues(current => ({ ...current, remarks: event.target.value }))} aria-label="Grade remarks" />{error && <small className="form-error">{error}</small>}</td><td><button className="icon-button" onClick={() => void save()} disabled={saving} title="Save grade" aria-label="Save grade"><Save size={16} /></button><button className="icon-button" onClick={() => setEditing(false)} title="Cancel" aria-label="Cancel"><X size={16} /></button></td></tr>;
return <tr><td>{studentKey(record)}</td><td>{studentName(record)}</td><td>{courseName(record)}</td><td>{valueAt(record, ['midterm_grade'])}%</td><td>{valueAt(record, ['final_grade'])}%</td><td>{valueAt(record, ['remarks'])}</td>{canEdit && <td><button className="text-button" onClick={() => setEditing(true)}><Pencil size={14} />Edit</button></td>}</tr> }

export function CoursesPage() { const [page, setPage] = useState(1); return <RecordsPage title="Courses" description="Course codes, names, units, and statuses from the API." endpoint="/courses" page={page} setPage={setPage}>{result => <Table><thead><tr><th>Course code</th><th>Course name</th><th>Units</th><th>Status</th></tr></thead><tbody>{result.data.map(record => <tr key={record.id}><td>{valueAt(record, ['code', 'course_code'])}</td><td>{valueAt(record, ['name', 'title', 'course_title', 'course_name'])}</td><td>{valueAt(record, ['units', 'unit'])}</td><td><span className={`status status-${valueAt(record, ['status'], 'unknown').toLowerCase()}`}>{valueAt(record, ['status'])}</span></td></tr>)}</tbody></Table>}</RecordsPage> }
